repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: [
          types-requests,
          types-click,
          numpy,
          torch,
          transformers,
          matplotlib,
          anthropic,
          openai,
          google-genai,
          ollama,
          typeguard,
          uvicorn,
          fastapi
        ]
        exclude: ^games/
        pass_filenames: false
        args: [--config-file=pyproject.toml, src/xega]
