repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: bash -lc 'uvx --from pyright pyright'
        types: [python]
        pass_filenames: false  # run once per commit over configured "include"
