name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --dev

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files

    - name: Run tests (excluding integration)
      run: uv run pytest -m "not integration"

    - name: Run integration tests
      run: uv run pytest -m "integration"
      timeout-minutes: 10
